### ISSUE TITLE
Quamash bug

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#273]

**Comment by M5oul** [comment]
An other crash, I did nothing:
```bash
  File "/home/moul/.pyenv/versions/cutecoin/lib64/python3.4/site-packages/quamash/__init__.py", line 89, in run
    r = callback(*args, **kwargs)
  File "/usr/lib64/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] Aucune adresse associée avec le nom de l'hôte
```

**Comment by Insoleet** [comment]
You probably lost your connection. This is a bug in quamash : https://github.com/harvimt/quamash/issues/42

**Comment by Insoleet** [comment]
Any chance you have the logs before this error ?

**Comment by M5oul** [comment]
No.

**Comment by Insoleet** [comment]
Can you check in your file ~/.cutecoin/cutecoin.log please ?

**Comment by M5oul** [comment]
My wire were disconnected during a while when it happend:
```bash
<center><h1>502 Bad Gateway</h1></center>^M
<hr><center>nginx/1.6.2</center>^M
</body>^M
</html>^M
)
Refresh nodes
Error : No peer answered in  community (0 peers available)
Error : No peer answered in  community (0 peers available)
Error : No peer answered in  community (0 peers available)
Error : No peer answered in  community (0 peers available)
Refresh status
Error : No peer answered in  community (0 peers available)
Timeout error : 8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU
Requesting connection info: moul.re:8999
Request : http://moul.re:8999/blockchain/current
Request : http://moul.re:8999/network/peering/peers
Timeout error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
Timeout error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
Requesting connection info: 88.174.120.187:45001
Request : http://88.174.120.187:45001/blockchain/current
Request : http://88.174.120.187:45001/network/peering/peers
Timeout error : CnRzLoh8BgBvjDSUFmqNXtxtf2SBoNb6jkzw3dw2r4Sh
Timeout error : CnRzLoh8BgBvjDSUFmqNXtxtf2SBoNb6jkzw3dw2r4Sh
Requesting connection info: metab.ucoin.io:9201
Request : http://metab.ucoin.io:9201/blockchain/current
Request : http://metab.ucoin.io:9201/network/peering/peers
Timeout error : HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
Timeout error : HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
Requesting connection info: ucoin.inso.ovh:80
Request : http://ucoin.inso.ovh:80/blockchain/current
Request : http://ucoin.inso.ovh:80/network/peering/peers
Exception handler executing
Future exception was never retrieved
future: <Future finished exception=gaierror(-5, "Aucune adresse associée avec le nom de l'hôte")>
Traceback (most recent call last):
  File "/home/moul/.pyenv/versions/cutecoin/lib64/python3.4/site-packages/quamash/__init__.py", line 89, in run
    r = callback(*args, **kwargs)
  File "/usr/lib64/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] Aucune adresse associée avec le nom de l'hôte
```

**Comment by Insoleet** [comment]
Can you try with the pushed fix ?

**Comment by M5oul** [comment]
I don't know how to reproduce it. Unplug/plug my wire doesn't works.

**Comment by Insoleet** [comment]
Well if it does not crash it's good sign it does not crash anymore :)

**Comment by M5oul** [comment]
Ok :smile_cat:

**Comment by M5oul** [comment]
I could reproduced It:
```bash
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/current
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/lookup/HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/node/summary
DEBUG:node:refresh_block:Requesting connection info: ucoin.inso.ovh:80
DEBUG:__init__:requests_get:Request : http://ucoin.inso.ovh:80/blockchain/current
DEBUG:__init__:requests_get:Request : http://ucoin.inso.ovh:80/network/peering/peers
DEBUG:__init__:requests_get:Request : http://ucoin.inso.ovh:80/network/peering
DEBUG:__init__:requests_get:Request : http://ucoin.inso.ovh:80/wot/lookup/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU
DEBUG:__init__:requests_get:Request : http://ucoin.inso.ovh:80/node/summary
DEBUG:node:refresh_block:Requesting connection info: metab.ucoin.fr:9201
DEBUG:__init__:requests_get:Request : http://metab.ucoin.fr:9201/blockchain/current
DEBUG:__init__:requests_get:Request : http://metab.ucoin.fr:9201/network/peering/peers
DEBUG:__init__:requests_get:Request : http://metab.ucoin.fr:9201/network/peering
DEBUG:__init__:requests_get:Request : http://metab.ucoin.fr:9201/wot/lookup/5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of
DEBUG:__init__:requests_get:Request : http://metab.ucoin.fr:9201/node/summary
DEBUG:node:refresh_block:Requesting connection info: moul.re:8999
DEBUG:__init__:requests_get:Request : http://moul.re:8999/blockchain/current
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering/peers
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering
DEBUG:__init__:requests_get:Request : http://moul.re:8999/wot/lookup/6YfbKWKkwsW2u8ZG168uHtpKd52cM66zqRSG5g44f6mg
DEBUG:__init__:requests_get:Request : http://moul.re:8999/node/summary
DEBUG:node:refresh_block: : 6YfbKWKkwsW2u8ZG168uHtpKd52cM66zqRSG5g44f6mg
DEBUG:node:refresh_peers: : 6YfbKWKkwsW2u8ZG168uHtpKd52cM66zqRSG5g44f6mg
DEBUG:node:refresh_informations: : 6YfbKWKkwsW2u8ZG168uHtpKd52cM66zqRSG5g44f6mg
DEBUG:node:refresh_uid: : 6YfbKWKkwsW2u8ZG168uHtpKd52cM66zqRSG5g44f6mg
DEBUG:node:refresh_summary: : 6YfbKWKkwsW2u8ZG168uHtpKd52cM66zqRSG5g44f6mg
DEBUG:node:refresh_block:Requesting connection info: moul.re:8999
DEBUG:__init__:requests_get:Request : http://moul.re:8999/blockchain/current
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering/peers
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Future exception was never retrieved
future: <Future finished exception=gaierror(-5, "Aucune adresse associée avec le nom de l'hôte")>
Traceback (most recent call last):
  File "/home/moul/.pyenv/versions/cutecoin/lib64/python3.4/site-packages/quamash/__init__.py", line 89, in run
    r = callback(*args, **kwargs)
  File "/usr/lib64/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] Aucune adresse associée avec le nom de l'hôte
```

**Comment by Insoleet** [comment]
With this workaround, it should not crash anymore.
