### ISSUE TITLE
Crash after network manual refresh

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#277]
As @M5oul noticed, ucoin@0.12.0 was making nodes unreachable (ahem... brilliant release).

Then I fixed it in 0.12.1, updated my nodes, manually refresh Sakia, and the crash occured.

```
future: <Task finished coro=<_rollback() done, defined at C:\projects\cutecoin\src\cutecoin\core\txhistory.py:323> exception=TypeError('<lambda>() takes 2 positional arguments but 3 were given',)>
Traceback (most recent call last):
  File "C:\Python34_64\envs\test-environment\lib\asyncio\tasks.py", line 238, in _step
  File "C:\projects\cutecoin\src\cutecoin\core\txhistory.py", line 350, in _rollback
  File "C:\projects\cutecoin\src\cutecoin\core\transfer.py", line 319, in run_state_transitions
  File "C:\projects\cutecoin\src\cutecoin\core\transfer.py", line 305, in _try_transition
TypeError: <lambda>() takes 2 positional arguments but 3 were given
```

**Comment by Insoleet** [comment]
Is it an old version of sakia ?

**Comment by c-geek** [comment]
It is a 0.11 I downloaded on November 23th.

**Comment by Insoleet** [comment]
Ok, I think this bug was fixed here : https://github.com/ucoin-io/sakia/commit/8a9f8f757137577eb957fc6d59be1bad71736f66
