### ISSUE TITLE
Sakia often crashes when it suddently looses the network

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#286]
I have an unstable WiFi connection here, and it often crashes.

Don't know if you can reproduce it, but I prefer to tell it in an issue.

**Comment by Insoleet** [comment]
I have an idea of the crash, but can you produce any logs / stacktrace of the crash ?

**Comment by c-geek** [comment]
Yep, catched it!

```
DEBUG:community_view:refresh_status:Refresh status
DEBUG:community_view:refresh_status:Error : No peer answered in  community (0 peers available)
DEBUG:decorators:task_done:Task already removed
DEBUG:decorators:task_done:Task already removed
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Future exception was never retrieved
future: <Future finished exception=gaierror(-2, 'Nom ou service inconnu')>
Traceback (most recent call last):
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/site-packages/quamash/__init__.py", line 89, in run
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/socket.py", line 533, in getaddrinfo
socket.gaierror: [Errno -2] Nom ou service inconnu
```

**Comment by Insoleet** [comment]
It's a quamash bug I thought I found a workaround but it seems not... Maybe I'll have to send a PR to quamash. https://github.com/harvimt/quamash/issues/42
