### ISSUE TITLE
Crash when lost connexion

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#294]
I lost connection with the wire, all node became red, then I click on refresh node, then sakia crashed:

```bash
DEBUG:__init__:requests_get:Request : http://ucoin.inso.ovh:80/network/peering/peers
DEBUG:node:refresh_peers:[Errno 101] Cannot connect to host ucoin.inso.ovh:80 ssl:False [Can not connect to ucoin.inso.ovh:80 [Le réseau n'est pas accessible]] : 8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU
DEBUG:network_tab:refresh_nodes:Refresh nodes
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
ERROR:network:data_node:Error : No peer answered in  community (0 peers available)
DEBUG:community_view:refresh_status:Refresh status
DEBUG:community_view:refresh_status:Error : No peer answered in  community (0 peers available)
DEBUG:node:refresh_block:[Errno 101] Cannot connect to host ucoin.inso.ovh:80 ssl:False [Can not connect to ucoin.inso.ovh:80 [Le réseau n'est pas accessible]] : 8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU
DEBUG:node:refresh_block:Requesting connection info: moul.re:8999
DEBUG:__init__:requests_get:Request : http://moul.re:8999/blockchain/current
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering/peers
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering
DEBUG:__init__:requests_get:Request : http://moul.re:8999/wot/lookup/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:__init__:requests_get:Request : http://moul.re:8999/node/summary
DEBUG:node:refresh_block:Requesting connection info: metab.ucoin.io:9201
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/current
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Future exception was never retrieved
future: <Future finished exception=gaierror(-5, "Aucune adresse associée avec le nom de l'hôte")>
Traceback (most recent call last):
  File "/home/moul/.pyenv/versions/env-sakia/lib/python3.5/site-packages/quamash/__init__.py", line 89, in run
    r = callback(*args, **kwargs)
  File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/socket.py", line 728, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] Aucune adresse associée avec le nom de l'hôte
```

**Comment by Insoleet** [comment]
Which version ? branch dev or release 0.11.2 ?

**Comment by M5oul** [comment]
dev branch.

**Comment by M5oul** [comment]
I reproduced it.

**Comment by Insoleet** [comment]
Yes it should happen with 0.11.2 too. My workaround was incorrect. I should try another one...
