### ISSUE TITLE
Sakia crash Ubuntu 14.04 / 64 bits

### ISSUE THREAD

**Issue by galuel** [ucoin-io/sakia#330]
```sh
>/build/exe.linux-x86_64-3.4$ ./sakia
Traceback (most recent call last):
  File "/home/travis/.pyenv/versions/sakia-env/lib/python3.4/site-packages/libnacl/__init__.py", line 81, in _get_nacl
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/ctypes/__init__.py", line 429, in LoadLibrary
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/ctypes/__init__.py", line 351, in __init__
OSError: tweetnacl.so: cannot open shared object file: No such file or directory

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/home/travis/.pyenv/versions/sakia-env/lib/python3.4/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "src/sakia/main.py", line 21, in <module>
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/travis/build/ucoin-io/sakia/src/sakia/gui/mainwindow.py", line 16, in <module>
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/travis/build/ucoin-io/sakia/src/sakia/gui/process_cfg_account.py", line 8, in <module>
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2212, in _find_and_load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/travis/.pyenv/versions/sakia-env/lib/python3.4/site-packages/ucoinpy/__init__.py", line 27, in <module>
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/travis/.pyenv/versions/sakia-env/lib/python3.4/site-packages/ucoinpy/key/__init__.py", line 1, in <module>
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/travis/.pyenv/versions/sakia-env/lib/python3.4/site-packages/ucoinpy/key/signing_key.py", line 9, in <module>
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2212, in _find_and_load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/travis/.pyenv/versions/sakia-env/lib/python3.4/site-packages/libnacl/__init__.py", line 89, in <module>
  File "/home/travis/.pyenv/versions/sakia-env/lib/python3.4/site-packages/libnacl/__init__.py", line 87, in _get_nacl
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,  and tweetnacl.so
````

**Comment by Insoleet** [comment]
You'll need to install libsodium : 
```
  wget http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium13_1.0.1-1_amd64.deb
  sudo dpkg -i libsodium13_1.0.1-1_amd64.deb
```

Should be handled better when we migrate to pyinstaller instead of cxFreeze.

**Comment by galuel** [comment]
ok, launched !
