### ISSUE TITLE
Sakia crashes every time I open the meta_b.

### ISSUE THREAD

**Issue by koeppelmann** [ucoin-io/sakia#337]
Using the latest mac version - sakia crashes directly after opening the community meta_b.:
```sh
Martins-MacBook-Pro:MacOS martin$ ./sakia -d
DEBUG:app:load:Loading data...
DEBUG:app:switch_language:Loading translations
DEBUG:node:from_json:{'currency': 'meta_brouzouf', 'endpoints': ['BASIC_MERKLED_API metab.ucoin.io 88.174.120.187 9201'], 'uid': 'cgeek', 'pubkey': 'HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk'}
DEBUG:node:from_json:Node from json : HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk,metab.ucoin.io,88.174.120.187,9201,None,meta_brouzouf,2,[]
DEBUG:network:add_node:HnFcS connected
DEBUG:app:load_cache:Merging network : {'version': '0.11.3', 'network': [{'currency': 'meta_brouzouf', 'fork_window': 0, 'software': '', 'pubkey': 'HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk', 'block': None, 'endpoints': ['BASIC_MERKLED_API metab.ucoin.io 88.174.120.187 9201'], 'version': '', 'uid': '', 'state': 1, 'last_change': 1452455467.116434}]}
DEBUG:node:from_json:{'currency': 'meta_brouzouf', 'fork_window': 0, 'software': '', 'pubkey': 'HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk', 'block': None, 'endpoints': ['BASIC_MERKLED_API metab.ucoin.io 88.174.120.187 9201'], 'version': '', 'uid': '', 'state': 1, 'last_change': 1452455467.116434}
DEBUG:node:from_json:Node from json : HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk,metab.ucoin.io,88.174.120.187,9201,None,meta_brouzouf,1,[]
DEBUG:network:handle_change:DA39A3EE5E -> DA39A3EE5E
DEBUG:mainwindow:refresh:Refresh started
DEBUG:mainwindow:refresh:{'auto_refresh': False, 'proxy_type': 'HTTP', 'account': 'koeppelmann', 'enable_proxy': False, 'ref': 0, 'proxy_port': 8080, 'lang': 'en_GB', 'expert_mode': False, 'notifications': True, 'proxy_address': '', 'international_system_of_units': True, 'maximized': False, 'digits_after_comma': 6}
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/0
DEBUG:node:refresh_block:Requesting connection info: metab.ucoin.io:9201
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/current
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/lookup/HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/node/summary
DEBUG:node:refresh_block:Changed block 47527 -> 47527
DEBUG:network:handle_change:DA39A3EE5E -> 00007FFD14
DEBUG:network:handle_change:Latest block changed : 47527
DEBUG:account:refresh_transactions:Start refresh transactions
DEBUG:wallet:refresh_transactions:Refresh transactions for Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47527
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47527
DEBUG:network:handle_change:00007FFD14 -> 00007FFD14
DEBUG:network:handle_change:00007FFD14 -> 00007FFD14
DEBUG:network:handle_change:00007FFD14 -> 00007FFD14
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47527
DEBUG:decorators:task_done:Task already removed
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:app:jsonify_accounts:{'koeppelmann': <sakia.core.account.Account object at 0x11175d168>}
DEBUG:node:jsonify_root_node:Saving root node : HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk,metab.ucoin.io,88.174.120.187,9201,47527,meta_brouzouf,1,[]
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47527
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/members
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/members
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/members
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/members
DEBUG:txhistory:_wait_for_previous_refresh:No previous refresh
DEBUG:txhistory:refresh:Starts a new refresh
DEBUG:txhistory:_refresh:Refresh from : 0 to 47527
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/ud/history/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/tx/sources/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/tx/sources/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/tx/sources/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/with/tx
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:decorators:task_done:Task already removed
DEBUG:decorators:task_done:Task already removed
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/172
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/memberships/BMAVuMDcGhYAV4wA27DL1VXX2ZARZGJYaMwpf7DJFMYH
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:access:simple_request:1 is not of type 'string'

Failed validating 'type' in schema['properties']['memberships']['items']['properties']['version']:
    {'type': 'string'}

On instance['memberships'][0]['version']:
    1
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/memberships/BMAVuMDcGhYAV4wA27DL1VXX2ZARZGJYaMwpf7DJFMYH
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:access:simple_request:1 is not of type 'string'

Failed validating 'type' in schema['properties']['memberships']['items']['properties']['version']:
    {'type': 'string'}

On instance['memberships'][0]['version']:
    1
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/memberships/BMAVuMDcGhYAV4wA27DL1VXX2ZARZGJYaMwpf7DJFMYH
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:access:simple_request:1 is not of type 'string'

Failed validating 'type' in schema['properties']['memberships']['items']['properties']['version']:
    {'type': 'string'}

On instance['memberships'][0]['version']:
    1
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:homescreen:click_on_tile:Click on tile
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/memberships/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:community:get_block:Requesting block 1
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/1
DEBUG:identities:refresh_identities:Refresh 0 identities
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/certifiers-of/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/parameters
DEBUG:community_view:refresh_status:Refresh status
DEBUG:community:get_block:Requesting block 47527
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/lookup/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:decorators:task_done:Task already removed
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:transactions_tab:dates_changed:Changed dates
DEBUG:txhistory:set_period:Filtering from 2015-01-21 00:00:00 to 2000-01-01 00:00:00
DEBUG:transactions_tab:dates_changed:Changed dates
DEBUG:txhistory:set_period:Filtering from 2015-01-21 00:00:00 to 2015-01-21 00:00:00
DEBUG:transactions_tab:dates_changed:Changed dates
DEBUG:txhistory:set_period:Filtering from 2015-01-21 00:00:00 to 2016-01-11 00:00:00
DEBUG:decorators:task_done:Task already removed
DEBUG:decorators:task_done:Task already removed
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/with/ud
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/certifiers-of/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47402
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47439
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47464
DEBUG:node:refresh_peers:Incorrect leaf reply
DEBUG:community_view:refresh_quality_buttons:UID Published
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47403
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47482
DEBUG:access:simple_request:1 is not of type 'string'

Failed validating 'type' in schema['properties']['memberships']['items']['properties']['version']:
    {'type': 'string'}

On instance['memberships'][0]['version']:
    1
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/memberships/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47497
DEBUG:access:simple_request:1 is not of type 'string'

Failed validating 'type' in schema['properties']['memberships']['items']['properties']['version']:
    {'type': 'string'}

On instance['memberships'][0]['version']:
    1
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/memberships/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47507
DEBUG:access:simple_request:1 is not of type 'string'

Failed validating 'type' in schema['properties']['memberships']['items']['properties']['version']:
    {'type': 'string'}

On instance['memberships'][0]['version']:
    1
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<reset() done, defined at /Users/travis/build/ucoin-io/sakia/src/sakia/gui/wot_tab.py:240> exception=UnboundLocalError("local variable 'json_data' referenced before assignment",)>
Traceback (most recent call last):
  File "/Users/travis/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 238, in _step
  File "/Users/travis/build/ucoin-io/sakia/src/sakia/gui/wot_tab.py", line 248, in reset
  File "/Users/travis/build/ucoin-io/sakia/src/sakia/core/account.py", line 249, in identity
  File "/Users/travis/build/ucoin-io/sakia/src/sakia/core/registry/identities.py", line 113, in future_find
  File "/Users/travis/build/ucoin-io/sakia/src/sakia/core/net/api/bma/access.py", line 284, in simple_request
UnboundLocalError: local variable 'json_data' referenced before assignment
```

**Comment by Insoleet** [comment]
Hello,

Hehe bad luck from you, @c-geek just changed the version of the nodes, so you found a rare bugs which happens only with 0.13 nodes and a cleared cache (which is your case since your came yesterday...)

It's easy to fix, thanks for the report.

**Comment by koeppelmann** [comment]
alright - so all I need to do is update to the latest version?

**Comment by Insoleet** [comment]
As soon as I publish the fix, which I'll do sometimes in the week, as soon as I find some free time ! :) Sorry for inconvenience !
