### ISSUE TITLE
Sakia 0.11.14 (label 0.11.13)

### ISSUE THREAD

**Issue by galuel** [ucoin-io/sakia#344]
Problem about refreshing transactions (it stays blocked at 99%, or even crashes at 99% it depends of a random choice apparently...) : 

```
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47486
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/block/47512
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/memberships/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:access:simple_request:1 is not of type 'string'

Failed validating 'type' in schema['properties']['memberships']['items']['properties']['version']:
    {'type': 'string'}

On instance['memberships'][0]['version']:
    1
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/memberships/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:access:simple_request:1 is not of type 'string'

Failed validating 'type' in schema['properties']['memberships']['items']['properties']['version']:
    {'type': 'string'}

On instance['memberships'][0]['version']:
    1
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/memberships/Ev72QW2CUnzZuoNLfEu9YKLUF8zXAbbCUHrhaveH6Ktv
DEBUG:access:simple_request:1 is not of type 'string'

Failed validating 'type' in schema['properties']['memberships']['items']['properties']['version']:
    {'type': 'string'}

On instance['memberships'][0]['version']:
    1
DEBUG:txhistory:_wait_for_previous_refresh:Previous refresh finished
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<_refresh() done, defined at /home/travis/build/ucoin-io/sakia/src/sakia/core/txhistory.py:234> exception=UnboundLocalError("local variable 'json_data' referenced before assignment",)>
Traceback (most recent call last):
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/asyncio/tasks.py", line 238, in _step
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/txhistory.py", line 272, in _refresh
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/txhistory.py", line 205, in _parse_block
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/txhistory.py", line 131, in _parse_transaction
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/registry/identities.py", line 113, in future_find
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/net/api/bma/access.py", line 284, in simple_request
UnboundLocalError: local variable 'json_data' referenced before assignment
```

**Comment by Insoleet** [comment]
Weird, this bug is supposed to be fixed. Did you clear your cache ? Did you install correctly the new release ? 
To be sure I will need to publish a new release.

**Comment by galuel** [comment]
I just made all the operation again and this time it is ok. I probably run the old 0.11.13 version and not the 0.11.14
