### ISSUE TITLE
Can't run dev branch

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#353]
Since a moment, I can't run Sakia excepted on `dev0114` branch,

on `dev` branch, I get:
```sh
  File "src/sakia/main.py", line 19, in <module>
    from quamash import QSelectorEventLoop
ImportError: cannot import name 'QSelectorEventLoop'
```

I fixed it when you changed `ucoin-python-api` and I could fixed it installing `requirement.txt`.

I tried to reinstalled requirements, with last pip:
```sh
(env-sakia) [moul@moulinette build]$ sudo pip install requirements.txt
Mot de passe [sudo] de moul :
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
```

Where am I missing something?

**Comment by Insoleet** [comment]
The correct command is `pip install --upgrade requirements.txt`

Please forget about using sudo in virtualenv ^^ sudo installs everything in the system, not in the virtualenv.

**Comment by M5oul** [comment]
Yep, you are right.

I still, get this error:
```sh
(env-sakia) [moul@moulinette build]$ pip install --upgrade requirements.txt 
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
```

Do you know what it could be?

**Comment by Insoleet** [comment]
Ups, wrong command. `pip install --upgrade -r requirements.txt`

**Comment by M5oul** [comment]
Thanks. It was written in documentation :smile:
Requirements had been installed, it didn't works after `pyenv rehash`.
I tried reinstall requierments, that time sakia start.
Do I need to `pyenv rehash`? It's possibly done after `pip`.

Finally, Sakia crash at startup on `dev` branch:
```sh
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering/peers
DEBUG:network:handle_change:000002C0EF -> 000002C0EF
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<refresh_informations() done, defined at /home/moul/projects/sakia/build/src/sakia/core/net/node.py:362> exception=AttributeError("'BlockId' object has no attribute 'split'",)>
Traceback (most recent call last):
  File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/moul/projects/sakia/build/src/sakia/core/net/node.py", line 377, in refresh_informations
    if BlockId.from_str(peer.blockid).number > BlockId.from_str(self.peer.blockid).number:
  File "/home/moul/.pyenv/versions/env-sakia/lib/python3.5/site-packages/ucoinpy/documents/block.py", line 32, in from_str
    data = blockid.split("-")
AttributeError: 'BlockId' object has no attribute 'split'
```

**Comment by Insoleet** [comment]
Can you try with this fix please ?

**Comment by M5oul** [comment]
It works! Thanks for your good job.
