### ISSUE TITLE
Membership renewal crash on 0.12.dev3

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#361]
```
future: <Task finished coro=<send_membership_demand() done, defined at sakia/gui/community_view.py:314> exception=TypeError('__init__() takes 9 positional arguments but 10 were given',)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/community_view.py", line 319, in send_membership_demand
  File "sakia/core/account.py", line 474, in send_membership
TypeError: __init__() takes 9 positional arguments but 10 were given
```

**Comment by M5oul** [comment]
I could reproduce it.
