### ISSUE TITLE
Crash while sending money

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#363]
```
future: <Task finished coro=<refresh_transfers() done, defined at sakia/models/txhistory.py:303> exception=AttributeError("'NoneType' object has no attribute 'number'",)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 237, in _step
  File "sakia/models/txhistory.py", line 329, in refresh_transfers
  File "asyncio/futures.py", line 385, in __iter__
  File "asyncio/tasks.py", line 288, in _wakeup
  File "asyncio/futures.py", line 274, in result
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/models/txhistory.py", line 262, in data_sent
AttributeError: 'NoneType' object has no attribute 'number'
```

**Comment by M5oul** [comment]
I could not reproduce it sending money from the button.
But, sending money to myself, make it crash. It seems to be same bug:
```bash
uts:\n0:D:44992:00000BEF6A63C53D46F460436E3AEE302927E7E9:1192988018518596\nOutputs:\nJ78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3:1\nJ78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3:1192988018518595\nComment: eiua\nL45y3i5AinTuDpD7w6VnByh271f9eUAm4ArUee6S3bwU1HVpwWElU+2jK7UIetPiWqlzhalYxSJHtqNk7OUWBw==\n'}
DEBUG:__init__:requests_post:POST : {'transaction': 'Version: 1\nType: Transaction\nCurrency: meta_brouzouf\nIssuers:\nJ78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3\nInputs:\n0:D:44992:00000BEF6A63C53D46F460436E3AEE302927E7E9:1192988018518596\nOutputs:\nJ78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3:1\nJ78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3:1192988018518595\nComment: eiua\nL45y3i5AinTuDpD7w6VnByh271f9eUAm4ArUee6S3bwU1HVpwWElU+2jK7UIetPiWqlzhalYxSJHtqNk7OUWBw==\n'}
DEBUG:transfer:_try_transition:40740 : TO_SEND --> REFUSED
DEBUG:toast:display:NOTIFY DISPLAY
DEBUG:community:get_block:Requesting block 1
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<refresh_transfers() done, defined at /home/moul/projects/sakia/build/src/sakia/models/txhistory.py:303> exception=AttributeError("'NoneType' object has no attribute 'number'",)>
Traceback (most recent call last):
  File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 237, in _step
    result = coro.throw(exc)
  File "/home/moul/projects/sakia/build/src/sakia/models/txhistory.py", line 329, in refresh_transfers
    gathered_list = await asyncio.gather(*requests_coro)
  File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/moul/projects/sakia/build/src/sakia/models/txhistory.py", line 262, in data_sent
    self.app, transfer.blockid.number)\
AttributeError: 'NoneType' object has no attribute 'number'
```

**Comment by c-geek** [comment]
It was not immediate for me, I first received some error message from nodes, retried to send money, and then it crashed.
