### ISSUE TITLE
Crash while creating a new account

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#364]
I've cleaned my .config/sakia folder to see if some bugs were coming from there, and then after the "Connect using identity" button (in the window with 3 vertical buttons with one giving the option to join as a guest) it crashed:

```
Task exception was never retrieved
future: <Task finished coro=<open_add_account_dialog() done, defined at sakia/gui/mainwindow.py:101> exception=AttributeError("'dict' object has no attribute 'contacts_changed'",)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/mainwindow.py", line 106, in open_add_account_dialog
  File "sakia/gui/mainwindow.py", line 156, in action_change_account
AttributeError: 'dict' object has no attribute 'contacts_changed'
```

**Comment by Insoleet** [comment]
Fixed : https://github.com/ucoin-io/sakia/commit/efa6d3f8df0e103e67cc7f788b61eaa35a80ee86
