### ISSUE TITLE
Can't certify in testnet

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#394]
When I try to certify @Insoleet, I get the following:

```
ERROR:<string>:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<refresh() done, defined at sakia/gui/certification.py:177> exception=TypeError('unorderable types: NoneType() > int()',)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/certification.py", line 193, in refresh
  File "sakia/core/registry/identity.py", line 489, in cert_issuance_delay
TypeError: unorderable types: NoneType() > int()

```

**Comment by Insoleet** [comment]
This should be fixed in latest dev version.

**Comment by c-geek** [comment]
Yep.
