### ISSUE TITLE
Crash de l'application

### ISSUE THREAD

**Issue by vincentux** [ucoin-io/sakia#398]
J'ai voulu éditer un contact dans l'onglet "Account" puis "Contacts" 
je choisi un membre et je clique sur "Edit" et là l'appli plante avec ce message 
```
DEBUG:Registering callback <bound method Future._set_result_unless_cancelled of <Future pending>> to be invoked with arguments (None,) after 15 second(s)
DEBUG:Adding callback <Handle Future._set_result_unless_cancelled(None)> with delay 15
DEBUG:Callback timer fired, calling <Handle BaseConnector._cleanup()>
DEBUG:Registering callback <bound method BaseConnector._cleanup of <aiohttp.connector.TCPConnector object at 0x7f344002d390>> to be invoked with arguments () after 23.998459551999986 second(s)
DEBUG:Adding callback <Handle BaseConnector._cleanup()> with delay 23.998459551999986
Traceback (most recent call last):
  File "sakia/gui/mainwindow.py", line 231, in edit_contact
  File "sakia/gui/contact.py", line 67, in edit_contact
  File "sakia/gui/contact.py", line 31, in __init__
TypeError: QDialog(QWidget parent=None, Qt.WindowFlags flags=0): argument 1 has unexpected type 'Account'
Abandon (core dumped)
```
pour info je ne suis pas encore membre de la monnaie (super_currency), est-ce que ça joue ?
_Version de Sakia : 0.20.0dev3_

**Comment by Insoleet** [comment]
Nice catch ;)
